# Generated by Django 2.1.7 on 2019-03-11 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_name', models.CharField(max_length=200)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('released_to_environment', models.BooleanField()),
                ('residue', models.BooleanField()),
                ('burned', models.BooleanField()),
                ('records_of_volume', models.BooleanField()),
                ('disposal', models.BooleanField()),
                ('recyclable_materials', models.BooleanField()),
                ('recycled_on_site', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=200)),
                ('street_address', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=16)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=32, null=True)),
                ('latest_inspection', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Letters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_subject', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=800)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deq.Checklist')),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deq.Facility'),
        ),
    ]
